/// Cases seeded into an empty database so a fresh checkout has something to
/// show.
///
/// `GET /api/get-smartpointer` against UAT always returns rows; against a
/// local server it returned nothing until someone uploaded a file, so the
/// dashboard's empty state was the first thing anyone saw and no screen past
/// it could be worked on. These rows close that gap.
///
/// They are written the way a real upload lands — the repository's column
/// names, every value text — so seeding goes through the same `importRows`
/// path as an import and cannot drift from it. CPU, team and the two category
/// columns are all values the client's master data recognises, so no seeded
/// row shows up flagged.
///
/// Seeding only ever happens into an empty table, and `CASES_SEED=0` turns it
/// off entirely — see `CasesRepository.seedIfEmpty`.
///
/// Every row carries one of the two statuses the workflow has — `Pending with
/// CPU` or `Pending with Health Checker` — because those are the only ones the
/// dashboard offers. Seeding anything else put states on the grid that no real
/// case can reach, which made the local dashboard look richer than the system
/// it stands in for.
const dummyCases = <Map<String, dynamic>>[
  {
    'client_id': '3332125',
    'customer_name': 'LEHRY INSTRUMENTATION AND VALVES PVT LTD',
    'account_no': '11424036',
    'line_no': '50301271033004',
    'health_check_category': 'FD Exceptions',
    'sub_category': 'Excess lien marked in Core',
    'support_system': '787920',
    'core_system': '986920',
    'exception_category': 'Exception',
    'reason': 'Fd Lien Amount Mismatch Between Lmm And Core; To Be Reviewed '
        'And Rectified',
    'cpu': 'Chennai',
    'team': 'Disbursement Team',
    'segment': '',
    'facility': '',
    'sr_no': '0',
    'maker': 'OFF550975',
    'checker': 'r14878',
    'ls_srm_date': '',
    'status': 'Pending with CPU',
  },
  {
    'client_id': '1130488',
    'customer_name': 'TRANSIT ELECTRONICS LTD',
    'account_no': '11264580',
    'line_no': '50301271033011',
    'health_check_category': 'CAM Expiry Health Check',
    'sub_category': 'CAM expired, renewal pending',
    'support_system': 'LMM',
    'core_system': 'FC',
    'exception_category': 'Exception',
    'reason': 'Cam Validity Lapsed; Renewal Note To Be Submitted',
    'cpu': 'Mumbai',
    'team': 'Cam Renewal Team',
    'segment': 'Corporate',
    'facility': 'Cash Credit',
    'sr_no': '1',
    'maker': 'OFF455430',
    'checker': 'r14878',
    'ls_srm_date': '2026-06-18',
    'status': 'Pending with CPU',
  },
  {
    'client_id': '4943581',
    'customer_name': 'ACME ENGINEERING PVT LTD',
    'account_no': '50200031339584',
    'line_no': '50301271033027',
    'health_check_category': 'Stock Statement Health Check',
    'sub_category': 'Stock statement overdue',
    'support_system': 'LMM',
    'core_system': 'FC',
    'exception_category': 'Exception',
    'reason': 'Stock Statement Not Received For Two Consecutive Months',
    'cpu': 'Gurgaon',
    'team': 'Stock Statement Team',
    'segment': 'SME',
    'facility': 'Working Capital',
    'sr_no': '2',
    'maker': 'OFF807292',
    'checker': 'r22104',
    'ls_srm_date': '2026-07-02',
    'status': 'Pending with Health Checker',
  },
  {
    'client_id': '2287410',
    'customer_name': 'NORTHGATE LOGISTICS LIMITED',
    'account_no': '11930442',
    'line_no': '50301271033039',
    'health_check_category': 'Insurance Expiry Health Check',
    'sub_category': 'Policy lapsed',
    'support_system': 'LMM',
    'core_system': 'FC',
    'exception_category': 'Exception',
    'reason': 'Insurance Policy Expired; Renewed Copy To Be Obtained',
    'cpu': 'Kolkata',
    'team': 'Insurance Team',
    'segment': 'Corporate',
    'facility': 'Term Loan',
    'sr_no': '3',
    'maker': 'OFF159515',
  'checker': 'r22104',
    'ls_srm_date': '2026-05-29',
    'status': 'Pending with Health Checker',
  },
  {
    'client_id': '7761203',
    'customer_name': 'SILVERLINE TEXTILES PVT LTD',
    'account_no': '11557781',
    'line_no': '50301271033046',
    'health_check_category': 'LMM vs UBS Mismatch',
    'sub_category': 'Limit mismatch between systems',
    'support_system': '450000',
    'core_system': '400000',
    'exception_category': 'Exception',
    'reason': 'Sanctioned Limit In Lmm Does Not Match Ubs; To Be Reconciled',
    'cpu': 'Ahmedabad',
    'team': 'Trade/ Limit Setting Team',
    'segment': 'SME',
    'facility': 'Letter of Credit',
    'sr_no': '4',
    'maker': 'OFF756549',
    'checker': 'r19052',
    'ls_srm_date': '2026-07-11',
    'status': 'Pending with CPU',
  },
  {
    'client_id': '5518890',
    'customer_name': 'VERTEX AGRO INDUSTRIES LTD',
    'account_no': '11002348',
    'line_no': '50301271033058',
    'health_check_category': 'Legal Document Health Check',
    'sub_category': 'Document pending execution',
    'support_system': 'LMM',
    'core_system': 'FC',
    'exception_category': 'Exclusion',
    'reason': 'Mortgage Deed Pending Registration; Excluded Till Legal '
        'Sign Off',
    'cpu': 'Mohali',
    'team': 'LAD Team',
    'segment': 'Agri',
    'facility': 'Overdraft',
    'sr_no': '5',
    'maker': 'OFF498090',
    'checker': 'r19052',
    'ls_srm_date': '2026-04-16',
    'status': 'Pending with Health Checker',
  },
  {
    'client_id': '9084412',
    'customer_name': 'BLUEPEAK INFRA PROJECTS LTD',
    'account_no': '11778120',
    'line_no': '50301271033063',
    'health_check_category': 'FD Exceptions',
    'sub_category': 'Lien not marked in Core',
    'support_system': '1250000',
    'core_system': '0',
    'exception_category': 'Exception',
    'reason': 'Fd Held As Security Has No Lien In Core; To Be Marked',
    'cpu': 'Chennai',
    'team': 'Disbursement Team',
    'segment': 'Corporate',
    'facility': 'Bank Guarantee',
    'sr_no': '6',
    'maker': 'OFF357501',
    'checker': 'r14878',
    'ls_srm_date': '2026-07-24',
    'status': 'Pending with CPU',
  },
  {
    'client_id': '6640117',
    'customer_name': 'MERIDIAN HEALTHCARE SERVICES PVT LTD',
    'account_no': '11669305',
    'line_no': '50301271033074',
    'health_check_category': 'CAM Expiry Health Check',
    'sub_category': 'Review overdue',
    'support_system': 'LMM',
    'core_system': 'FC',
    'exception_category': 'Exception',
    'reason': 'Annual Review Overdue By More Than Thirty Days',
    'cpu': 'Mumbai',
    'team': 'Cam Updation Team',
    'segment': 'SME',
    'facility': 'Cash Credit',
    'sr_no': '7',
    'maker': 'OFF972798',
    'checker': 'r22104',
    'ls_srm_date': '2026-06-30',
    'status': 'Pending with CPU',
  },
];
