name: smart_monitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^3.6.1
  csv: ^8.0.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.3
  web: ^1.1.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  excel: ^4.0.6

flutter:
  uses-material-design: true
